# Generated by Django 5.0.1 on 2025-10-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cartitem_unique_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Panier", "verbose_name_plural": "Paniers"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Article du panier",
                "verbose_name_plural": "Articles du panier",
            },
        ),
    ]
