# Generated by Django 5.0.1 on 2025-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_adminpanel",
            field=models.BooleanField(
                default=False,
                help_text="Indique si cet utilisateur peut accéder au panneau d'administration",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_employee",
            field=models.BooleanField(
                default=False,
                help_text="Indique si cet utilisateur peut accéder à la fonctionnalité de scan QR",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="key1",
            field=models.CharField(
                blank=True,
                help_text="Clé secrète générée automatiquement à la création de l'utilisateur",
                max_length=64,
            ),
        ),
    ]
