# Generated by Django 5.0.1 on 2025-09-17 20:14

import apps.tickets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key2",
                    models.CharField(
                        help_text="Clé secrète générée à l'achat", max_length=64
                    ),
                ),
                (
                    "final_key",
                    models.CharField(
                        help_text="Clé finale = key1 + key2",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image QR code du billet",
                        null=True,
                        upload_to=apps.tickets.models.qr_code_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("valid", "Valide"), ("used", "Utilisé")],
                        default="valid",
                        help_text="Statut du billet",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Commande associée à ce billet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billet",
                "verbose_name_plural": "Billets",
                "db_table": "tickets_ticket",
                "ordering": ["-created_at"],
            },
        ),
    ]
