# Generated by Django 5.0.1 on 2025-09-17 20:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("solo", "Solo (1 personne)"),
                            ("duo", "Duo (2 personnes)"),
                            ("familiale", "Familiale (4 personnes)"),
                        ],
                        help_text="Type d'offre (solo, duo, familiale)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Nombre de personnes pour cette offre"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de l'offre en euros",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'offre est disponible à la vente",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description détaillée de l'offre"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre",
                "verbose_name_plural": "Offres",
                "db_table": "catalog_offer",
                "ordering": ["price"],
            },
        ),
    ]
